version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.06.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    networks:
     pihole_network:
       ipv4_address: 172.39.0.2
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: password
      DNSMASQ_LISTENING: local
      PIHOLE_DNS_: '172.39.0.3#5053'
    # Volumes store your data between container upgrades
    volumes:
      - './volumes/pihole/pihole:/etc/pihole'
      - './volumes/pihole/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: klutchell/unbound:1.25.1
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    networks: 
     pihole_network:
       ipv4_address: 172.39.0.3
    volumes:
      - './volumes/unbound:/opt/unbound/etc/unbound/'
    restart: unless-stopped
networks:
    pihole_network:
      driver: bridge
      ipam:
        config:
          - subnet: 172.39.0.0/24
