services:
  beszel-hub:
    image: henrygd/beszel:latest
    container_name: beszel-hub
    restart: unless-stopped
    networks:
      - homelab_bridge
    environment:
      APP_URL: https://observability.localhost/
    volumes:
      - ./volumes/beszel_data:/beszel_data
      - ./volumes/beszel_socket:/beszel_socket
    healthcheck:
      test: [ 'CMD', '/beszel', 'health', '--url', 'http://localhost:8090' ]
      start_period: 5s
      interval: 120s

networks:
  homelab_bridge:
    name: homelab_bridge
    external: true