---
- name: Configure the database host.
  hosts: database_host
  gather_facts: false
  become: true

  handlers:
    - name: reboot-pi
      ansible.builtin.reboot:

  tasks:
    - name: Set quieter PoE Hat fan profiles.
      ansible.builtin.blockinfile:
        path: /boot/config.txt
        block: |
          # PoE Hat Fan Speeds
          dtoverlay=rpi-poe
          dtparam=poe_fan_temp0=50000
          dtparam=poe_fan_temp0_hyst=1000
          dtparam=poe_fan_temp1=60000
          dtparam=poe_fan_temp1_hyst=2500
          dtparam=poe_fan_temp2=70000
          dtparam=poe_fan_temp2_hyst=5000
          dtparam=poe_fan_temp3=80000
          dtparam=poe_fan_temp3_hyst=5000
      notify: reboot-pi

    - name: Ensure cgroups are configured correctly in cmdline.txt.
      ansible.builtin.replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "cgroup_memory=1"
        - "cgroup_enable=memory"
      notify: reboot-pi

    - name: Ensure required dependencies are installed.
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-setuptools
          - build-essential
          - golang
          - git
          - acl
        state: present
        update_cache: true
      become: true

    - name: Ensure required Python libraries are installed.
      ansible.builtin.pip:
        name:
          - openshift
          - pyyaml
          - pexpect
        state: present
      become: true

- name: Configure PSQL on the database host.
  hosts: database_host
  gather_facts: true
  become: true

  handlers:
    - name: restart-postgres
      ansible.builtin.service:
        name: postgresql
        state: restarted
      become: true

  tasks:
    - name: Install PostgreSQL.
      ansible.builtin.package:
        name:
          - postgresql
        state: present
        update_cache: true
      become: true

    - name: Ensure Postgres is configured to listen to all ip addresses
      ansible.builtin.lineinfile:
        path: /etc/postgresql/13/main/postgresql.conf
        line: listen_addresses = '*'
        create: yes
      become: true
      notify: restart-postgres

    - name: Ensure Postgres is configured to allow connections from the same network
      ansible.builtin.lineinfile:
        path: /etc/postgresql/13/main/pg_hba.conf
        line: host     all             all            samenet              md5
        create: yes
      become: true
      notify: restart-postgres

    - name: Create 'pi' database user
      become: yes
      become_user: postgres
      ansible.builtin.expect:
        command: createuser pi --pwprompt --superuser --createdb --replication
        responses:
          'Enter password for new role:': 'pi'
          'Enter it again:': 'pi'
    - name: Get service facts
      ansible.builtin.service_facts:

    - name: Verify PostgreSQL service is running
      ansible.builtin.fail:
        msg: PostgreSQL is not present, why? It should have been there!
      when: ansible_facts.services["postgresql.service"] is not defined
