---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    repoURL: 'https://github.com/baumac/baumac'
    path: ./
    targetRevision: HEAD
    directory:
      recurse: true
      include: '{apps/*/deploy/argocd-app.yaml,infra/pi-cluster/argocd/apps/*.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
