# argocd-apps.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  sources:
    - repoURL: 'https://github.com/baumac/baumac'
      path: apps/
      targetRevision: HEAD
      directory:
        recurse: true
        include: '*/deploy/*.yaml'
    - repoURL: 'https://github.com/baumac/baumac'
      path: infra/argocd/apps
      targetRevision: HEAD
      directory:
        recurse: true
        include: '*.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
