apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konnect-kic-controller
spec:
  project: default
  source:
    path: infra/pi-cluster/argocd/apps/konnect-kong-proxies/
    repoURL: 'https://github.com/baumac/baumac'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-kic-controller.yaml
  destination:
    namespace: konnect-kic
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
