export const MAX_EMAIL_LENGTH = 255

export const MAX_PASSWORD_LENGTH = 255
export const MIN_PASSWORD_LENGTH = 8
export const MIN_PASSWORD_LOWERCASE = 1
export const MIN_PASSWORD_UPPERCASE = 1
export const MIN_PASSWORD_NUMBERS = 1
export const MIN_PASSWORD_SYMBOLS = 1
