---
name: PSQL Database CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  lint-yaml:
    name: Lint all of the PSQL Database YAML files.
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.4'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint all of the infra YAML files
        run: cd ./infra/psql-database && yamllint .
